In [55]:
import pandas as pd

In [56]:
data = pd.read_csv("../data/games/betting.csv")

In [57]:
len(data)

9486

In [58]:
data.head(20)

,date,season,week,home_team,home_wins,away_team,away_wins,home_last_season_wins,away_last_season_wins,favorite,...,neutral,playoff,score_home,score_away,home_win,fav_win,cover,spread_diff,over_under_result,over_under_diff
0,09/02/1978,1978,1,Tampa Bay Buccaneers,0,New York Giants,0,NaN,NaN,Tampa Bay Buccaneers,...,False,False,13,19,False,False,False,-8.0,NaN,NaN
1,09/03/1978,1978,1,Atlanta Falcons,0,Houston Oilers,0,NaN,NaN,NaN,...,False,False,20,14,True,False,NaN,NaN,NaN,NaN
2,09/03/1978,1978,1,Buffalo Bills,0,Pittsburgh Steelers,0,NaN,NaN,NaN,...,False,False,17,28,False,False,NaN,NaN,NaN,NaN
3,09/03/1978,1978,1,Chicago Bears,0,St. Louis Cardinals,0,NaN,NaN,NaN,...,False,False,17,10,True,False,NaN,NaN,NaN,NaN
4,09/03/1978,1978,1,Cincinnati Bengals,0,Kansas City Chiefs,0,NaN,NaN,NaN,...,False,False,23,24,False,False,NaN,NaN,NaN,NaN
5,09/03/1978,1978,1,Cleveland Browns,0,San Francisco 49ers,0,NaN,NaN,NaN,...,False,False,24,7,True,False,NaN,NaN,NaN,NaN
6,09/03/1978,1978,1,Denver Broncos,0,Oakland Raiders,0,NaN,NaN,NaN,...,False,False,14,6,True,False,NaN,NaN,NaN,NaN
7,09/03/1978,1978,1,Detroit Lions,0,Green Bay Packers,0,NaN,NaN,NaN,...,False,False,7,13,False,False,NaN,NaN,NaN,NaN
8,09/03/1978,1978,1,New England Patriots,0,Washington Redskins,0,NaN,NaN,NaN,...,False,False,14,16,False,False,NaN,NaN,NaN,NaN
9,09/03/1978,1978,1,New Orleans Saints,0,Minnesota Vikings,0,NaN,NaN,NaN,...,False,False,31,24,True,False,NaN,NaN,NaN,NaN
10,09/03/1978,1978,1,New York Jets,0,Miami Dolphins,0,NaN,NaN,NaN,...,False,False,33,20,True,False,NaN,NaN,NaN,NaN
11,09/03/1978,1978,1,Philadelphia Eagles,0,Los Angeles Rams,0,NaN,NaN,NaN,...,False,False,14,16,False,False,NaN,NaN,NaN,NaN
12,09/03/1978,1978,1,Seattle Seahawks,0,San Diego Chargers,0,NaN,NaN,NaN,...,False,False,20,24,False,False,NaN,NaN,NaN,NaN
13,09/04/1978,1978,1,Dallas Cowboys,0,Baltimore Colts,0,NaN,NaN,NaN,...,False,False,38,0,True,False,NaN,NaN,NaN,NaN
14,09/09/1978,1978,2,Tampa Bay Buccaneers,0,Detroit Lions,0,NaN,NaN,NaN,...,False,False,7,15,False,False,NaN,NaN,NaN,NaN
15,09/10/1978,1978,2,Baltimore Colts,0,Miami Dolphins,0,NaN,NaN,NaN,...,False,False,0,42,False,False,NaN,NaN,NaN,NaN
16,09/10/1978,1978,2,Buffalo Bills,0,New York Jets,0,NaN,NaN,NaN,...,False,False,20,21,False,False,NaN,NaN,NaN,NaN
17,09/10/1978,1978,2,Cleveland Browns,0,Cincinnati Bengals,0,NaN,NaN,NaN,...,False,False,13,10,True,False,NaN,NaN,NaN,NaN
18,09/10/1978,1978,2,Green Bay Packers,0,New Orleans Saints,0,NaN,NaN,NaN,...,False,False,28,17,True,False,NaN,NaN,NaN,NaN
19,09/10/1978,1978,2,Kansas City Chiefs,0,Houston Oilers,0,NaN,NaN,NaN,...,False,False,17,20,False,False,NaN,NaN,NaN,NaN

In [59]:
data['season'].dtypes

dtype('int64')

In [60]:
data['over_under_diff'].describe()

count    9262.000000
mean        0.619337
std        13.682436
min       -39.000000
25%        -9.000000
50%         0.000000
75%         9.500000
max        68.500000
Name: over_under_diff, dtype: float64

In [62]:
data['over_under_result'].describe()

count      9084
unique        2
top       Under
freq       4605
Name: over_under_result, dtype: object

In [61]:
data['spread_diff'].describe()

count    9122.000000
mean       -0.121574
std        13.388211
min       -52.000000
25%        -8.500000
50%        -0.500000
75%         8.500000
max        50.500000
Name: spread_diff, dtype: float64

In [63]:
data['cover'].describe()

count      9122
unique        2
top       False
freq       4831
Name: cover, dtype: object